# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9eb92cd1629019b36c667f96bc0f8c24aad263321aebf33d31212186ba9dc6c15b58c4f694e24249790dbaaeae98530b12204d98f6cf9965114c391d0e4e59c

test:
  secret_key_base: f35a91cf7331fe53bf4dcba097ae7cc47c74793a511ec75c51499db7bcd5b8437a4c4c38547ed1a57af66d25428a49638e6726ad09d92dd6da853e62896cf7c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
